# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Command: pre-commit install
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: debug-statements
        language_version: python3

-   repo: github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        language_version: python3

-   repo: github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        language_version: python3

-   repo: github.com/asottile/setup-cfg-fmt
    rev: 2.2.0
    hooks:
    -   id: setup-cfg-fmt
        language_version: python3

-   repo: github.com/asottile/add-trailing-comma
    rev: 2.3.0
    hooks:
    -   id: add-trailing-comma
        language_version: python3

-   repo: github.com/asottile/pyupgrade
    rev: 3.2.2
    hooks:
    -   id: pyupgrade
        language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus, --add-import, 'from __future__ import absolute_import']
        language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy

# add Jinja linter